### ISSUE TITLE
pages setup

### ISSUE THREAD

**Issue by rvilarl** [vexflow/vexflow-examples#1]
@ronyeh @jaredjj3 can you help me on how to use pages to get the html files served by github?

**Comment by jaredjj3** [comment]
1. Create and commit an index.html file. This is what Github pages serves as the landing page.
2. Link other files using anchor tags relative to your project root on index.html. Consider renaming your directory from `html` to `static` and add tags like:

```html
<a href="static/step0.html">Go to Step 0</a>
```

3. Enable GitHub Pages. Go to your GitHub repository. Click on the 'Settings' tab. Scroll down to the 'GitHub Pages' section. For 'Source', select the branch you want to deploy from. After a few moments, you should see a link to your live site. It will be something like: https://username.github.io/your-repository-name/.

**Comment by rvilarl** [comment]
@jaredjj3 thanks it works, I was missing the index.html file. In the meanwhile I found another method which complains about "Uncaught ReferenceError: Vex is not defined". I will not use this method but I wonder if there is a problem in step0.html.

https://htmlpreview.github.io/?https://github.com/vexflow/vexflow-examples/blob/main/static/step0.html

however now that pages works this direct access has no problem

https://vexflow.github.io/vexflow-examples/static/step0.html

how could I solve the problem with htmlpreview?

**Comment by rvilarl** [comment]
@ronyeh @jaredjj3 @0xfe @mscuthbert @AaronDavidNewman @sschmidTU could you check if you have font problems (i.e.: squares) loading this page?

https://vexflow.github.io/vexflow-examples

I did not find a way to present the code directly below the score. Tips also apprecited.

**Comment by mscuthbert** [comment]
No square boxes on iPhone.

**Comment by rvilarl** [comment]
The pages is now using vexflow 4 so it is not posible to get square boxes :(. I have to wait for a new release of vexflow 5.

**Comment by rvilarl** [comment]
Ok now using vexflow 5, thanks @ronyeh, and the layout is wrong.

@jaredjj3 any idea why? You are getting it right in VexMl

https://vexflow.github.io/vexflow-examples/static/step0.html

**Comment by jaredjj3** [comment]
I suspect that it's `vexflow.EasyScore`, but that would be surprising since the [tests](https://github.com/vexflow/vexflow/actions/runs/6511466194/job/17687222324#step:5:34) are passing. Have you tried the lower level `vexflow` APIs to confirm?

**Comment by rvilarl** [comment]
https://vexflow.github.io/vexflow-examples/static/step2a.html does not use easyscore. To me it seems like the size of the fonts used in the internal calculations is bigger that the actual one.

**Comment by jaredjj3** [comment]
Good point. Another guess is that I don't see a `vexflow.Formatter` anywhere. Do you need to use that to format the voices?

**Comment by rvilarl** [comment]
I have included a step3 using lower level API and same problem

https://vexflow.github.io/vexflow-examples/static/step3.html

**Comment by rvilarl** [comment]
@AaronDavidNewman this is the problem that you described in https://github.com/vexflow/vexflow/issues/86 how did you solve it? how do you suggest to use await in these examples?

**Comment by rvilarl** [comment]
The problem is now resolved waiting for the font to load. The code is also shown using highlight.js.
